#!/bin/bash
#PBS -N test_cray_8
#PBS -l nodes=8:ppn=24
#PBS -l walltime=01:00:00
#PBS -j oe

# load modules  
. ~/load_modules.sh
module switch PrgEnv-gnu/6.0.4 PrgEnv-cray
#module load perftools-base
#module load perftools-preload

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=1
export PRGENV=cray
export OPENDIHU_HOME=/lustre/cray/ws9/2/ws/icbbnmai-opendihu0/opendihu-${PRGENV}

# this script needs OPENDIHU_HOME set
# <number of available nodes>
./run.py $PBS_NUM_NODES

