void RHS_routineForAVX(double * restrict X0, double * restrict X1, double * restrict X2, double * restrict X3, double * restrict X4, double * restrict X5, double * restrict X6, double * restrict X7, double * restrict X8, double * restrict X9,
                      double * restrict X10,double * restrict X11,double * restrict X12,double * restrict X13,double * restrict X14,double * restrict X15,double * restrict X16,double * restrict X17,double * restrict X18,double * restrict X19,
                      double * restrict X20,double * restrict X21,double * restrict X22,double * restrict X23,double * restrict X24,double * restrict X25,double * restrict X26,double * restrict X27,double * restrict X28,double * restrict X29,
                      double * restrict X30,double * restrict X31,double * restrict X32,double * restrict X33,double * restrict X34,double * restrict X35,double * restrict X36,double * restrict X37,double * restrict X38,double * restrict X39,
                      double * restrict X40,double * restrict X41,double * restrict X42,double * restrict X43,double * restrict X44,double * restrict X45,double * restrict X46,double * restrict X47,double * restrict X48,double * restrict X49,
                      double * restrict X50,double * restrict X51,double * restrict X52,double * restrict X53,double * restrict X54,double * restrict X55,double * restrict X56,int N, //the number of existing cells. also the length of all the double vectors we have a pointer for
                      double * restrict X_t0, double * restrict X_t1, double * restrict X_t2, double * restrict X_t3, double * restrict X_t4, double * restrict X_t5, double * restrict X_t6, double * restrict X_t7, double * restrict X_t8, double * restrict X_t9,
                      double * restrict X_t10,double * restrict X_t11,double * restrict X_t12,double * restrict X_t13,double * restrict X_t14,double * restrict X_t15,double * restrict X_t16,double * restrict X_t17,double * restrict X_t18,double * restrict X_t19,
                      double * restrict X_t20,double * restrict X_t21,double * restrict X_t22,double * restrict X_t23,double * restrict X_t24,double * restrict X_t25,double * restrict X_t26,double * restrict X_t27,double * restrict X_t28,double * restrict X_t29,
                      double * restrict X_t30,double * restrict X_t31,double * restrict X_t32,double * restrict X_t33,double * restrict X_t34,double * restrict X_t35,double * restrict X_t36,double * restrict X_t37,double * restrict X_t38,double * restrict X_t39,
                      double * restrict X_t40,double * restrict X_t41,double * restrict X_t42,double * restrict X_t43,double * restrict X_t44,double * restrict X_t45,double * restrict X_t46,double * restrict X_t47,double * restrict X_t48,double * restrict X_t49,
                      double * restrict X_t50,double * restrict X_t51,double * restrict X_t52,double * restrict X_t53,double * restrict X_t54,double * restrict X_t55,double * restrict X_t56,
                      double * restrict Gamma, double * restrict StimValue, double * restrict L_hs, clock_t * restrict handle_array, double * restrict portions_array);

//void fun(double* rates, int c);