# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

testcases = [
  "cuboid_hodgkin_huxley_cn",
  "cuboid_shorten_cn",
  "cuboid_hodgkin_huxley_ie",
  "cuboid_shorten_ie",
]

for testcase in testcases:
  env.Program(target = testcase, source = "src/{}.cpp".format(testcase))
